import mongoose from 'mongoose';
import { toJSONPlugin, contentPlugin } from './plugins.js';

export const SERVICE_ICONS = [
  'cap',
  'school',
  'library',
  'book-open',
  'notebook-pen',
  'clipboard-check',
  'file-check',
  'document',
  'pen-tool',
  'presentation',
  'award',
  'languages',
  'plane',
  'globe',
  'passport',
  'luggage',
  'map',
  'pin',
  'compass',
  'ticket',
  'flag',
  'coins',
  'banknote',
  'piggy-bank',
  'wallet',
  'credit-card',
  'hand-coins',
  'percent',
  'calculator',
  'users',
  'user-check',
  'user-plus',
  'handshake',
  'headphones',
  'message-circle',
  'phone',
  'mail',
  'heart',
  'life-buoy',
  'shield',
  'shield-check',
  'badge-check',
  'circle-check',
  'star',
  'thumbs-up',
  'lock',
  'key',
  'target',
  'search',
  'briefcase',
  'building-2',
  'clock',
  'timer',
  'calendar',
  'calendar-check',
  'home',
  'trending-up',
  'chart-bar',
  'list-checks',
  'layers',
  'lightbulb',
  'rocket',
  'sparkles',
  'settings',
  'send',
  'bookmark',
  'gift',
  'scale',
  'stethoscope',
  'laptop',
];

const serviceSchema = new mongoose.Schema(
  {
    slug: { type: String, required: true, unique: true, lowercase: true, trim: true },
    title: { type: String, required: [true, 'Title is required'], trim: true },
    description: { type: String, default: '', trim: true, maxlength: 600 },
    icon: { type: String, enum: SERVICE_ICONS, default: 'target' },
  },
  { timestamps: true },
);

serviceSchema.plugin(toJSONPlugin);
serviceSchema.plugin(contentPlugin);

export const Service = mongoose.model('Service', serviceSchema);
